name: "bluebell"
mode: "dev"
port: 8080
version: "v0.0.1"
machine_id: 1
start_time: "2021-03-31"
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 1.15.97.250
  port: 3306
  user: "root"
  password: "root"
  dbname: "sql_demo"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 1.15.97.250
  port: 6379
  password: ""
  db: 0
  pool_size: 100