## docker-compose模式，定义并运行多个容器（本项目暂时未用到联合容器，所以此处无用）
## yaml 配置
#version: "3.7"
#services:
#  mysql8019:
#    image: "mysql:5.7"
#    ports:
#      - "3306:3306"
#    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_DATABASE: "bluebell"
#      MYSQL_PASSWORD: "root"
#    volumes:
#      - ./init.sql:/data/application/init.sql
#  redis507:
#    image: "redis:5.0.7"
#    ports:
#      - "6379:6379"
#  bluebell_app:
#    build: .
#    command: sh -c "./wait-for.sh mysql57:3306 -- ./bubble ./conf/config.yaml"
#    depends_on:
#      - mysql57
#    ports:
#      - "8888:8888"